name: Deploy Node Application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t keshavagrawal18/worldwise-react --build-arg VITE_BASE_URL=${{secrets.VITE_BASE_URL}} .
      - name: Publish Image to docker hub
        run: docker push keshavagrawal18/worldwise-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull keshavagrawal18/worldwise-react:latest
      - name: Delete old container
        run: docker rm -f node-js-app-container
      - name: Run Docker Container
        run: docker run -d -p 5173:5173 --name reactjs-app-container keshavagrawal18/worldwise-react
